version: "3.9"

services:
  backend:
    build: ./backend
    container_name: comments-backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    volumes:
      - ./backend:/app/backend
      - static:/app/backend/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: comments-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    env_file:
      - .env

  redis:
    image: redis:7
    container_name: comments-redis
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    container_name:
      comments-nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - backend

volumes:
  postgres_data:
  static:
